### ISSUE TITLE
Babel 7 / newer, non-legacy decorator plugin

### ISSUE THREAD

**Issue by IngwiePhoenix** [heydoctor/express-marshal#1]
Hello!

I'd like to know if I can use this module while using the newer Babel and it's accompaning module for translating decorators?

Thanks!

**Comment by kylealwyn** [comment]
Yep! You'll just need to set the legacy option to true:

```json
{
   "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
   ]
}
```

**Comment by IngwiePhoenix** [comment]
Cool, thanks!

Just a question of curiosity: Why doesn’t this work with the legacy option turned off? I was playing around with this for a while now and couldn’t get a class decorator to work...

**Comment by kylealwyn** [comment]
This package uses the legacy decorator plugin for Babel 6.  https://github.com/kylealwyn/express-marshal/blob/master/.babelrc#L3

There's a note in the babel docs regarding using legacy decorator alongside the class property plugin, which sounds like it might be the issue: https://babeljs.io/docs/en/babel-plugin-proposal-decorators#note-compatibility-with-babel-plugin-proposal-class-properties

**Comment by IngwiePhoenix** [comment]
I am testing without the property proposal at all.

```js
function classDecorator(value) {
  //console.log("class", value, arguments.length, arguments)
  return function decorator(target) {
    let obj = {
      kind: "field",
      key: "isDecorated",
      placement: "static",
      descriptor: {
        configurable: false,
        enumerable: false,
        writeable: false,
      },
      method: () => {console.log("class rt mtd"); return true},
      value: true
    }
    target.elements.push(obj)
    console.log(target)
    return target
  }
}

function methodDecorator(value) {
  //console.log("method", value, arguments.length, arguments)
  return (target) => {
    //console.log("method rt", arguments)
    target.descriptor.value.isDecorated = true
    return target
  }
}

@classDecorator("class val")
class Bar {
  @methodDecorator("mtd val")
  baz() {
    console.log("foo")
  }
}

console.log(Bar, Bar.isDecorated, Bar.prototype.isDecorated)
// Expected to see the class and "true".
```

`.babelrc`:
```json
{
  "presets": [
    ["@babel/preset-env", {
      "targets": { "node": "current" }
    }]
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", {
      "decoratorsBeforeExport": true
    }]
  ]
}
```

Any idea here?

**Comment by kylealwyn** [comment]
It looks like you're attempting to add a property to the parent class from a method. Caused me some confusion when I first dove into decorators. I'd recommend looking through the source code of this package - but in short, you have to assign to the target's constructor in method decorators and inspect the target in the class decorator.

in method decorator, push new route onto route stack:
https://github.com/kylealwyn/express-marshal/blob/master/lib/index.js#L108

in class decorator, loop through routes and add to express router:
https://github.com/kylealwyn/express-marshal/blob/master/lib/index.js#L37

**Comment by IngwiePhoenix** [comment]
Well I was just playing around, trying to just drop a property on a method and a class to see how it works. The `methodDecorator` works - but the `classDecorator` doesn't.

Looking at what you linked, I realize that the usage shown on the decorator plugin's website entry is actually depicting it's "legacy" use. Looks like Babel got some documentation to do. :)

Well, as it seems, they are changing decorators soon and upgrading it to stage 2 soon anyway. Oh well. I'll just stick to `legacy` for now, then. :) Thanks for your help!
